/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Javamain */

#ifndef _Included_Javamain
#define _Included_Javamain
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Javamain
 * Method:    test
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Javamain_test
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
